# Build component for different platforms
name: build CI test

on:
  push:
    branches-ignore: [ "doc_test" ]
  pull_request:
    branches: [ "master", "dev" , "experimental" ]

jobs:
  tests:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - docs/examples/max-hon.yaml
          - docs/examples/max-smartair2.yaml
          - docs/examples/min-hon.yaml
          - docs/examples/min-smartair2.yaml


    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.3
    - name: Install esphome
      run: pip3 install -U esphome
    - name: Version esphome
      run: esphome version
    - name: Prepering test file
      run: cat .base.yaml ${{ matrix.file }} > __test__.yaml
    - name: Build ESPHome config
      run: esphome compile __test__.yaml
